services:
  forum:
    build: .
    container_name: forum

    ports:
      - "8080:8080"

    environment:
      FORUM_ADDRESS: ":8080"
      FORUM_DATABASE_PATH: "/app/data/forum.db"
      FORUM_SESSION_DURATION: "24h"
      FORUM_COOKIE_NAME: "forum_session"
      FORUM_SECURE_COOKIE: "false"

    volumes:
      - forum-data:/app/data

    restart: unless-stopped
volumes:
  forum-data:
    name: forum-data